#Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test, build and deploy Node.js app to Your-World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  all_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: npm install and build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          mv build ../backend/
      - name: npm install and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
          
      - name: run pm2
        run: |
          cd backend
          npm install pm2 -g
          pm2 start index.js
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          project: ./frontend

  build:
    runs-on: ubuntu-latest
    needs: all_tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: npm install and build frontend
        run: |
          cd frontend
          npm install
          npm run build --if-present
          mv build ../backend/
      - name: npm install and build backend
        run: |
          cd backend
          npm install
          npm run build --if-present
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./backend/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Your-World'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F547F3DB44334BBB98C0C814EF1FDB26 }}
          package: .
