name: Test, build and deploy Node.js app to Your-World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  all_tests:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: http://localhost:3001/
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0

      - name: npm install and build frontend
        run: |
          cd frontend
          npm install
          npm run build
          mv build ../backend/what
      - name: npm install and build backend
        run: |
          cd backend
          npm install
      - name: Run back-end tests
        run: |
          cd backend
          npx jest
      - name: Run node
        run: |
          cd backend
          node server.js &
      - name: Wait on server to start
        run: npx wait-on http://localhost:3001
      # - name: Run front-end tests
      #   run: |
      #     cd frontend
      #     npx cypress run
      - uses: cypress-io/github-action@v5
        with:
            working-directory: ./frontend
            wait-on: 'http://localhost:3001'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
      - name: Download all workflow run 
        if: failure()
        uses: actions/download-artifact@v3
  deploy:
    runs-on: ubuntu-latest
    needs: all_tests
    env:
      REACT_APP_API_URL: https://your-world.herokuapp.com/
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: npm install and build frontend
        run: |
          cd frontend
          npm install
          npm run build
          mv build ../backend/what
      - name: npm install and build backend
        run: |
          cd backend
          npm install
      - uses: akhileshns/heroku-deploy@v3.12.13 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "your-world"
          heroku_email: "waterdude50@gmail.com"
          appdir: "backend"
        env:
          MONGO_URL: ${{secrets.MONGO_URL}}
          JWT_KEY: ${{secrets.JWT_KEY}}
