#Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test, build and deploy Node.js app to Your-World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  all_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
      - name: npm install and build backend
        run: |
          cd backend
          npm install
      - name: Run front-end tests
        run: |
          cd backend
          npx jest
      - name: Run node
        run: |
          cd backend
          node server.js &
      - name: Wait on server to start
        run: npx wait-on http://localhost:3000
      - name: Cypress run
        run: |
          cd frontend
          npx cypress run

  deploy:
    runs-on: ubuntu-latest
    needs: all_tests
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "your-world" #Must be unique in Heroku
          heroku_email: "waterdude50@gmail.com"
          appdir: "backend" # <- This will point to the api folder in your proje
